#!/bin/sh
set -e
BUILD="${2:-$(mktemp -d)}"
./st "$BUILD" "$BUILD"
./dmenu "$BUILD" "$BUILD"
./slstatus "$BUILD" "$BUILD"
./dwm "$BUILD" "$BUILD"
cp -r "$BUILD/bin" "$BUILD/share" "${1:-/usr/local}/"
